[tool.ruff]
# A list of rule codes or prefixes to enable
select = ["B", "E", "F", "I", "N", "ANN", "PL"]
# A list of rule codes or prefixes to ignore
ignore = ["F401", "F841", "W505", "ARG"]

# A list of rule codes or prefixes to consider autofixable
fixable = ["A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"]
# A list of rule codes or prefixes to consider non-autofix-able.
unfixable = ["F401", "F841", "W505", "ARG"]

# Exclude a variety of commonly ignored directories.
exclude = [
    "__pypackages__",
    ".git",
    ".git-rewrite",
    ".venv",
    "data",
    "images",
    "logs",
    "ML",
    "snaps",
]

# The directories to consider when resolving first- vs. third-party imports.
src = ["src"]

# The tabulation size to calculate line length.
tab-size = 4

# Same as Black.
line-length = 150

# The minimum Python version to target
target-version = "py310"
